name: CICD

on:
  workflow_dispatch:
    inputs:
      service:
        options:
          - api
        required: true
        type: choice
        description: Choose which service to run

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
    - name: Build and Push Inventory API
      uses: docker/build-push-action@v2
      id: docker_build_api
      with:
        context: ./
        file: ./src/Inventory.Web.Host/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:inventory_api

    # Verification step for API
    - name: Verify API
      run: echo ${{ steps.docker_build_api.outputs.digest }}_api
